### ISSUE TITLE
Fails to build with Boost >= 1.65

### ISSUE THREAD

**Issue by fxcoudert** [fph/bastet#6]
With recent compiler (latest clang, e.g. from Xcode 9 on macOS) and latest boost (1.65), the compilation fails because:

```
./BastetBlockChooser.hpp:26:10: fatal error: 'boost/tr1/tr1/unordered_set' file not found
#include <boost/tr1/tr1/unordered_set>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is available as system header under the name `#include <unordered_set>`

**Comment by fph** [comment]
Thanks for the report!
I switched away from the system `unordered_set` to the boost one because the former did not work everywhere (see #1). I'll look into it -- I just have to look for a portable way to include that library. :(

Can you please tell me if `#include <boost/unordered_set>` works on your system?

**Comment by fxcoudert** [comment]
Yes, `#include <boost/unordered_set>` works.

**Comment by fph** [comment]
OK, I have switched to `boost/unordered_set`. I hope it works now (and that there are no regression for everyone else). Thanks!
